version: '3.8'
services:
  ollama:
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    volumes:
      - ~/.ollama/models:/root/.ollama/models

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      - "OLLAMA_API_URL=http://ollama:11434"
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=friday_service
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=friday
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U friday_service -d friday"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama: {}
  open-webui: {}
  qdrant-data: {}
  postgres-data: {}