version: '3.8'
services:
  ollama:
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    volumes:
      - ~/.ollama/models:/root/.ollama/models

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      - "OLLAMA_API_URL=http://ollama:11434"
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway

#  friday:
#    container_name: friday
#    build: ./friday
#    ports:
#      - "4000:4000"
#    environment:
#      - PORT=4000
#      - OLLAMA_API_URL=http://ollama:11434
#      - VECTOR_DB_TYPE=qdrant
#      - QDRANT_URL=http://qdrant:6333
#      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
#      - LLM_MODEL=llama3
#    depends_on:
#      - ollama
#      - qdrant
#    volumes:
#      - friday-data:/app/data
#    restart: unless-stopped

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

#  dashboard:
#    container_name: dashboard
#    build: ./dashboard
#    ports:
#      - "5000:5000"
#    environment:
#      - FRIDAY_API_URL=http://friday:4000
#    depends_on:
#      - friday
#    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
#  friday-data: {}
  qdrant-data: {}
